#!/bin/bash

BU2='\033[1;34m\033[44m'
BU3='\033[1;36m\033[46m'
R='\033[1;31m\033[41m'
OR='\033[1;31m\033[43m'
G='\033[1;32m\033[42m'
Y='\033[1;33m\033[43m'
BU1='\033[0;34m\033[44m'
B='\033[0;30m\033[40m'
WB='\033[1;30m\033[47m'
W='\033[0;37m\033[47m'
P='\033[0;35m\033[45m'
PU='\033[1;37m\033[45m'


clear
I=0
while [ $I -ne 10 ]; do
	echo ''
	I=$(($I + 1))
done

echo -e "\033[;32m"
echo '             xXXXX   xXXX
            XXXXXXX XXXXXX
            "XXXXXX XXXXXX
             XXXXX  XXXXX xXx
         XXXx XXXXX  XX" XXXX
         XXXXx "XX"  "  XXXXXX
          XXXXX   xXx  XXXXX"	  _____   __    __       __
           """  xXXXXXx "XX"	 /___  \ | | \  | |     /  \
              XXXXXXXXXX          ___| | | |\ \ | |    /  _ \
           xXXXXXXXXXXXXXx       /  ___/ | | \ \| |   /  /_\ \
           XXXXXXXXXXXXXXX       | |___  | |  \ | |  /  ____  \   __
            """"  """""""        \_____\ |_|   \|_| /__/    \__\ |=_|
			'

I=0
while [ $I -ne 10 ]; do
	echo ''
	I=$(($I + 1))
done

sleep 1

clear
I=0
while [ $I -ne 10 ]; do
	echo ''
	I=$(($I + 1))
done

echo -e "\033[;32m"
echo '             xXXXX   xXXX
            XXXXXXX XXXXXX
            "XXXXXX XXXXXX
             XXXXX  XXXXX xXx
         XXXx XXXXX  XX" XXXX
         XXXXx "XX"  "  XXXXXX
          XXXXX   xXx  XXXXX"	  _____   __    __       __
           """  xXXXXXx "XX"	 /___  \ | | \  | |     /  \
              XXXXXXXXXX          ___| | | |\ \ | |    /  _ \
           xXXXXXXXXXXXXXx       /  ___/ | | \ \| |   /  /_\ \
           XXXXXXXXXXXXXXX       | |___  | |  \ | |  /  ____  \   __   __
            """"  """""""        \_____\ |_|   \|_| /__/    \__\ |=_| |=_|
			'

I=0
while [ $I -ne 10 ]; do
	echo ''
	I=$(($I + 1))
done

sleep 1

clear
I=0
while [ $I -ne 10 ]; do
	echo ''
	I=$(($I + 1))
done

echo -e "\033[;32m"
echo '             xXXXX   xXXX
            XXXXXXX XXXXXX
            "XXXXXX XXXXXX
             XXXXX  XXXXX xXx
         XXXx XXXXX  XX" XXXX
         XXXXx "XX"  "  XXXXXX
          XXXXX   xXx  XXXXX"	  _____   __    __       __
           """  xXXXXXx "XX"	 /___  \ | | \  | |     /  \
              XXXXXXXXXX          ___| | | |\ \ | |    /  _ \
           xXXXXXXXXXXXXXx       /  ___/ | | \ \| |   /  /_\ \
           XXXXXXXXXXXXXXX       | |___  | |  \ | |  /  ____  \   __   __   __
            """"  """""""        \_____\ |_|   \|_| /__/    \__\ |=_| |=_| |=_|
			'

I=0
while [ $I -ne 10 ]; do
	echo ''
	I=$(($I + 1))
done

sleep 1

echo “Do you want nyan? \(YES/NO\)”
read answer

if [[ $answer == YES ]];

then 

while [ 1 ]; do

echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$R>$R>$R>$R>$R>$R>$R>$R>$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$R>$R>$R>$R>$R>$R>$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$R>$R>$R>$R>$R>$R>$R>$R>$OR&$OR&$OR&$OR&$OR&$B'$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$P-$PU\$$PU\$$PU\$$PU\$$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$PU\$$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$B'$PU\$$P-$PU\$$PU\$$W@$B'$BU1,$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$B'$PU\$$PU\$$PU\$$W@$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$B'$B'$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$B'$WB*$WB*$WB*$PU\$$PU\$$PU\$$W@$B'$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$WB*$WB*$B'$B'$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$WB*$WB*$B'$B'$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$G#$G#$G#$G#$G#$G#$G#$G#$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$B'$WB*$WB*$B'$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$P-$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$B'$B'$WB*$WB*$B'$W@$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$W.$B'$WB*$WB*$WB*$WB*$W.$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$B'$B'$B'$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$WB*$WB*$B'$WB*$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$G#$G#$G#$G#$G#$G#$G#$G#$BU3=$BU3=$BU3=$BU3=$B'$B'$W@$W@$PU\$$PU\$$PU\$$P-$PU\$$PU\$$B'$WB*$PU%$PU%$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$PU%$PU%$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$W.$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU2;$BU2;$BU2;$BU2;$B'$B'$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$WB*$WB*$WB*$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$WB*$WB*$B'$B'$BU1,$B'$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$B'$WB*$B'$BU1,$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU1,$BU1,$BU1,$BU1,$BU1,$W.$BU1,$BU1,$BU2;$BU2;$BU2;$W.$BU2;$BU2;$BU2;$BU2;$BU1,$BU1,$BU1,$B'$B'$B'$B'$BU1,$BU1,$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$BU1,$BU1,$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"

sleep 0.1
clear

echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$R>$R>$R>$R>$R>$R>$R>$R>$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$R>$R>$R>$R>$R>$R>$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$R>$R>$R>$R>$R>$R>$R>$R>$OR&$OR&$OR&$OR&$OR&$B'$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$P-$PU\$$PU\$$PU\$$PU\$$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$PU\$$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$B'$P-$PU\$$PU\$$W@$B'$BU1,$BU1,$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$B'$PU\$$PU\$$W@$B'$BU1,$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$Y+$Y+$Y+$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$PU\$$PU\$$W@$B'$B'$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$Y+$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$WB*$B'$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$G#$G#$G#$G#$G#$G#$G#$G#$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$WB*$B'$B'$B'$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$WB*$WB*$WB*$WB*$B'$W@$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$W.$B'$WB*$WB*$WB*$WB*$W.$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$B'$B'$WB*$WB*$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$WB*$WB*$B'$WB*$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$G#$G#$G#$G#$G#$G#$G#$G#$BU3=$BU3=$BU3=$B'$B'$B'$W@$W@$PU\$$PU\$$PU\$$P-$PU\$$PU\$$PU\$$B'$WB*$PU%$PU%$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$PU%$PU%$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU2;$BU2;$BU2;$BU2;$BU2;$B'$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$WB*$WB*$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$WB*$WB*$B'$BU1,$B'$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$WB*$WB*$B'$BU1,$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU1,$BU1,$BU1,$W.$BU1,$BU1,$BU1,$BU1,$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$BU1,$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"

sleep 0.1
clear


echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$W."$BU1,
echo -e "$R>$R>$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$R>$R>$R>$R>$R>$R>$R>$R>$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$R>$R>$R>$R>$R>$R>$R>$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$R>$R>$R>$R>$R>$R>$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$P-$PU\$$PU\$$PU\$$PU\$$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$PU\$$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$B'$P-$PU\$$PU\$$W@$B'$BU1,$BU1,$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$OR&$OR&$OR&$OR&$OR&$OR&$OR&$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$B'$PU\$$PU\$$W@$B'$BU1,$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$PU\$$PU\$$W@$B'$B'$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$Y+$Y+$Y+$Y+$Y+$Y+$Y+$G#$G#$G#$G#$G#$G#$G#$G#$Y+$Y+$Y+$Y+$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$B'$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$B'$B'$B'$B'$B'$W@$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$W.$B'$WB*$WB*$WB*$WB*$W.$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$G#$G#$G#$G#$G#$G#$G#$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$G#$B'$WB*$WB*$WB*$WB*$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$WB*$WB*$B'$WB*$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$B'$B'$B'$BU3=$B'$W@$W@$PU\$$PU\$$PU\$$P-$PU\$$PU\$$PU\$$B'$WB*$PU%$PU%$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$PU%$PU%$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$W.$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$WB*$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$W.$BU1,$W.$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$WB*$WB*$B'$BU1,$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$WB*$WB*$B'$BU1,$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$W.$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"

sleep 0.1
clear


echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$W.$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$R>$R>$R>$R>$R>$R>$R>$R>$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$R>$R>$R>$R>$R>$R>$R>$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$R>$R>$R>$R>$R>$R>$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$P-$PU\$$PU\$$PU\$$PU\$$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$PU\$$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$B'$P-$PU\$$PU\$$W@$B'$BU1,$BU1,$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$OR&$OR&$OR&$OR&$OR&$OR&$OR&$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$B'$PU\$$PU\$$W@$B'$BU1,$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$PU\$$PU\$$W@$B'$B'$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$Y+$Y+$Y+$Y+$Y+$Y+$Y+$G#$G#$G#$G#$G#$G#$G#$G#$Y+$Y+$Y+$Y+$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$B'$B'$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$B'$B'$WB*$WB*$B'$W@$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$W.$B'$WB*$WB*$WB*$WB*$W.$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$G#$G#$G#$G#$G#$G#$G#$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$G#$G#$WB*$WB*$WB*$WB*$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$WB*$WB*$B'$WB*$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$B'$WB*$B'$BU3=$BU3=$B'$W@$W@$PU\$$PU\$$PU\$$P-$PU\$$PU\$$PU\$$B'$WB*$PU%$PU%$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$PU%$PU%$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU3=$BU3=$B'$BU3=$BU3=$BU3=$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$WB*$WB*$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU2;$BU2;$BU2;$BU2;$BU2;$B'$WB*$WB*$B'$BU1,$B'$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$WB*$B'$BU1,$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$BU1,$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"

sleep 0.1
clear


echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$W.$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$R>$R>$R>$R>$R>$R>$R>$R>$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$R>$R>$R>$R>$R>$R>$R>$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$R>$R>$R>$R>$R>$R>$R>$R>$OR&$OR&$OR&$OR&$OR&$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$P-$PU\$$PU\$$PU\$$PU\$$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$PU\$$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$B'$PU\$$P-$PU\$$PU\$$W@$B'$BU1,$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$Y+$Y+$Y+$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$B'$PU\$$PU\$$PU\$$W@$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$B'$WB*$WB*$WB*$PU\$$PU\$$PU\$$W@$B'$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$B'$B'$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$G#$G#$G#$G#$G#$G#$G#$G#$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$WB*$WB*$B'$B'$B'$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$B'$WB*$WB*$WB*$WB*$B'$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$P-$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$B'$B'$B'$B'$WB*$B'$W@$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$W.$B'$WB*$WB*$WB*$WB*$W.$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$G#$G#$G#$G#$G#$G#$G#$G#$BU3=$BU3=$BU3=$B'$B'$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$WB*$WB*$B'$WB*$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$B'$W@$W@$PU\$$PU\$$PU\$$P-$PU\$$PU\$$B'$WB*$PU%$PU%$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$PU%$PU%$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU2;$BU2;$BU2;$BU2;$B'$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$B'$B'$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$WB*$WB*$WB*$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU1,$BU1,$B'$WB*$WB*$B'$BU1,$B'$WB*$WB*$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$WB*$WB*$BU1,$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$BU1,$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"

sleep 0.1
clear


echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$R>$R>$R>$R>$R>$R>$R>$R>$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$R>$R>$R>$R>$R>$R>$R>$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$R>$R>$R>$R>$R>$R>$R>$R>$OR&$OR&$OR&$OR&$OR&$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$B'$B'$PU\$$PU\$$PU\$$W@$W@$B'$BU1,$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$PU\$$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$B'$P-$PU\$$PU\$$W@$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$Y+$Y+$Y+$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$PU\$$PU\$$PU\$$W@$B'$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$Y+$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$WB*$B'$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$G#$G#$G#$G#$G#$G#$G#$G#$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$WB*$B'$B'$B'$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$WB*$WB*$WB*$WB*$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$P-$B'$WB*$WB*$WB*$W.$B'$WB*$WB*$WB*$WB*$W.$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$B'$B'$WB*$WB*$B'$W@$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$WB*$WB*$B'$WB*$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$G#$G#$G#$G#$G#$G#$G#$G#$BU3=$BU3=$BU3=$B'$B'$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$PU%$PU%$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$PU%$PU%$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$B'$W@$W@$PU\$$PU\$$PU\$$P-$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU2;$BU2;$BU2;$BU2;$B'$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$W."$BU1,
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$WB*$B'$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$W."$BU1,
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$WB*$WB*$WB*$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU1,$BU1,$B'$WB*$WB*$B'$BU1,$B'$WB*$WB*$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$WB*$WB*$BU1,$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$W.$W.$BU1,$W."$BU1,
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$W."$BU1,

sleep 0.1
clear


echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$R>$R>$R>$R>$R>$R>$R>$R>$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$R>$R>$R>$R>$R>$R>$R>$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$R>$R>$R>$R>$R>$R>$B'$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$P-$PU\$$PU\$$PU\$$PU\$$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$PU\$$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$B'$PU\$$P-$PU\$$PU\$$W@$B'$BU1,$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$B'$PU\$$PU\$$PU\$$W@$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$OR&$OR&$OR&$OR&$OR&$OR&$OR&$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$OR&$B'$B'$B'$OR&$OR&$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$B'$WB*$WB*$WB*$PU\$$PU\$$PU\$$W@$B'$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$WB*$B'$B'$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$WB*$WB*$B'$B'$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$Y+$Y+$Y+$Y+$Y+$Y+$Y+$G#$G#$G#$G#$G#$G#$G#$G#$Y+$Y+$B'$WB*$WB*$B'$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$P-$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$B'$B'$WB*$WB*$B'$W@$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$W.$B'$WB*$WB*$WB*$WB*$W.$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$B'$B'$B'$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$WB*$WB*$B'$WB*$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$G#$G#$G#$G#$G#$G#$G#$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$G#$G#$G#$G#$G#$B'$B'$W@$W@$PU\$$PU\$$PU\$$P-$PU\$$PU\$$B'$WB*$PU%$PU%$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$PU%$PU%$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU3=$BU3=$BU3=$BU3=$BU3=$B'$B'$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$W.$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$WB*$WB*$WB*$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$W.$BU1,$BU1,$BU1,$W.$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$WB*$WB*$B'$B'$BU1,$B'$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$B'$WB*$WB*$BU1,$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU2;$BU2;$BU2;$BU2;$B'$B'$B'$B'$BU1,$BU1,$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$BU1,$BU1,$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$W.$BU1,$BU1,$BU1,$BU1,$BU1,$W.$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"

sleep 0.1
clear


echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$W.$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$R>$R>$R>$R>$R>$R>$R>$R>$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$R>$R>$R>$R>$R>$R>$R>$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$R>$R>$R>$R>$R>$R>$B'$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$P-$PU\$$PU\$$PU\$$PU\$$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$PU\$$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$B'$P-$PU\$$PU\$$W@$B'$BU1,$BU1,$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$B'$PU\$$PU\$$W@$B'$BU1,$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$OR&$OR&$OR&$OR&$OR&$OR&$OR&$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$PU\$$PU\$$W@$B'$B'$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$Y+$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$WB*$B'$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$Y+$Y+$Y+$Y+$Y+$Y+$Y+$G#$G#$G#$G#$G#$G#$G#$G#$Y+$B'$WB*$B'$B'$B'$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$WB*$WB*$WB*$WB*$B'$W@$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$W.$B'$WB*$WB*$WB*$WB*$W.$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$B'$B'$WB*$WB*$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$WB*$WB*$B'$WB*$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$G#$G#$G#$G#$G#$G#$G#$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$G#$G#$G#$G#$B'$B'$B'$W@$W@$PU\$$PU\$$PU\$$P-$PU\$$PU\$$PU\$$B'$WB*$PU%$PU%$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$PU%$PU%$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$B'$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$W.$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$WB*$WB*$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$WB*$WB*$B'$BU1,$B'$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$WB*$WB*$B'$BU1,$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU2;$BU2;$BU2;$BU2;$BU2;$B'$B'$B'$BU1,$BU1,$BU1,$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$W.$BU1,$BU1,$BU1,$BU1,$W.$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"

sleep 0.1
clear


echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$W.$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$R>$R>$R>$R>$R>$R>$R>$R>$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$R>$R>$R>$R>$R>$R>$R>$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$R>$R>$R>$R>$R>$R>$R>$R>$OR&$OR&$OR&$OR&$OR&$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$P-$PU\$$PU\$$PU\$$PU\$$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$PU\$$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$B'$P-$PU\$$PU\$$W@$B'$BU1,$BU1,$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$Y+$Y+$Y+$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$B'$PU\$$PU\$$W@$B'$BU1,$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$PU\$$PU\$$W@$B'$B'$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$G#$G#$G#$G#$G#$G#$G#$G#$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$G#$G#$G#$G#$G#$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$B'$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$B'$B'$B'$B'$B'$W@$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$W.$B'$WB*$WB*$WB*$WB*$W.$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$G#$G#$G#$G#$G#$G#$G#$G#$B'$WB*$WB*$WB*$WB*$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$WB*$WB*$B'$WB*$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$B'$B'$B'$BU3=$B'$W@$W@$PU\$$PU\$$PU\$$P-$PU\$$PU\$$PU\$$B'$WB*$PU%$PU%$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$PU%$PU%$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU2;$BU2;$BU2;$BU2;$BU2;$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$WB*$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU1,$BU1,$BU1,$BU1,$BU1,$B'$WB*$WB*$B'$BU1,$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$WB*$WB*$B'$W.$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"

sleep 0.1
clear


echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$W.$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$R>$R>$R>$R>$R>$R>$R>$R>$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$R>$R>$R>$R>$R>$R>$R>$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$R>$R>$R>$R>$R>$R>$R>$R>$OR&$OR&$OR&$OR&$OR&$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$P-$PU\$$PU\$$PU\$$PU\$$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$PU\$$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$B'$P-$PU\$$PU\$$W@$B'$BU1,$BU1,$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$Y+$Y+$Y+$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$B'$PU\$$PU\$$W@$B'$BU1,$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$PU\$$PU\$$W@$B'$B'$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$G#$G#$G#$G#$G#$G#$G#$G#$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$G#$G#$G#$G#$G#$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$B'$B'$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$B'$B'$WB*$WB*$B'$W@$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$W.$B'$WB*$WB*$WB*$WB*$W.$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$G#$G#$G#$G#$G#$G#$G#$G#$BU3=$WB*$WB*$WB*$WB*$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$WB*$WB*$B'$WB*$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$B'$WB*$B'$BU3=$BU3=$B'$W@$W@$PU\$$PU\$$PU\$$P-$PU\$$PU\$$PU\$$B'$WB*$PU%$PU%$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$PU%$PU%$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU2;$B'$BU2;$BU2;$BU2;$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$WB*$WB*$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU1,$BU1,$BU1,$BU1,$B'$WB*$WB*$B'$BU1,$B'$WB*$B'$BU1,$BU1,$W.$W.$BU1,$W.$WB*$WB*$B'$BU1,$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$BU1,$B'$B'$BU1,$BU1,$BU1,$BU1,$W.$BU1,$B'$B'$B'$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$W.$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"

sleep 0.1
clear


echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$W.$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$R>$R>$R>$R>$R>$R>$R>$R>$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$R>$R>$R>$R>$R>$R>$R>$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$R>$R>$R>$R>$R>$R>$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$P-$PU\$$PU\$$PU\$$PU\$$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$PU\$$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$B'$PU\$$P-$PU\$$PU\$$W@$B'$BU1,$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$OR&$OR&$OR&$OR&$OR&$OR&$OR&$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$B'$PU\$$PU\$$PU\$$W@$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$B'$WB*$WB*$WB*$PU\$$PU\$$PU\$$W@$B'$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$B'$B'$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$Y+$Y+$Y+$Y+$Y+$Y+$Y+$G#$G#$G#$G#$G#$G#$G#$G#$B'$WB*$WB*$B'$B'$B'$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$B'$WB*$WB*$WB*$WB*$B'$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$P-$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$B'$B'$B'$B'$WB*$B'$W@$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$W.$B'$WB*$WB*$WB*$WB*$W.$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$G#$G#$G#$G#$G#$G#$G#$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$G#$G#$G#$G#$B'$B'$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$WB*$WB*$B'$WB*$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$B'$W@$W@$PU\$$PU\$$PU\$$P-$PU\$$PU\$$B'$WB*$PU%$PU%$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$PU%$PU%$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU3=$BU3=$BU3=$BU3=$BU3=$B'$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$B'$B'$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$WB*$WB*$WB*$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU2;$BU2;$BU2;$B'$WB*$WB*$B'$W.$B'$WB*$WB*$W.$W.$BU1,$BU1,$BU1,$BU1,$B'$WB*$WB*$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$BU1,$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$BU1,$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$W.$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"

sleep 0.1
clear


echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$R>$R>$R>$R>$R>$R>$R>$R>$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$R>$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$R>$R>$R>$R>$R>$R>$R>$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$R>$R>$R>$R>$R>$R>$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$W@$W@$W@$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$B'$B'$PU\$$PU\$$PU\$$W@$W@$B'$BU1,$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$PU\$$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$B'$P-$PU\$$PU\$$W@$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$OR&$OR&$OR&$OR&$OR&$OR&$OR&$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$OR&$OR&$OR&$OR&$OR&$OR&$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$PU\$$PU\$$PU\$$W@$B'$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$Y+$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$P-$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$Y+$B'$WB*$B'$Y+$Y+$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$Y+$Y+$Y+$Y+$Y+$Y+$Y+$G#$G#$G#$G#$G#$G#$G#$G#$Y+$B'$WB*$B'$B'$B'$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$WB*$WB*$WB*$WB*$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$P-$B'$WB*$WB*$WB*$W.$B'$WB*$WB*$WB*$WB*$W.$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$G#$B'$B'$WB*$WB*$B'$W@$PU\$$P-$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$WB*$WB*$B'$WB*$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$G#$G#$G#$G#$G#$G#$G#$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$G#$G#$G#$G#$B'$B'$B'$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$PU%$PU%$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$PU%$PU%$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$B'$W@$W@$PU\$$PU\$$PU\$$P-$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$B'$B'$B'$B'$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU3=$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU3=$W.$BU3=$BU3=$BU3=$B'$B'$W@$W@$W@$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$PU\$$B'$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$W.$B'$WB*$B'$B'$W@$W@$W@$W@$W@$W@$W@$W@$W@$W@$B'$B'$B'$B'$B'$B'$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$B'$WB*$WB*$WB*$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$B'$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU2;$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$W.$BU2;$BU2;$BU2;$B'$WB*$WB*$B'$BU1,$B'$WB*$WB*$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$WB*$WB*$B'$B'$WB*$WB*$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$B'$B'$B'$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"
echo -e "$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$W.$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1,$BU1"

sleep 0.1
clear

done

else

echo "You are bored :c"
fi
